### ISSUE TITLE
CSS color improvements for readability in Chat Notifications

### ISSUE THREAD

**Issue by apoapostolov** [cs96and/FoundryVTT-CGMP#1]
It would be much better if we can get improved color choices or color options to customize to themes (for games that use Whetstone, or Color Highlights mods). 

![image](https://user-images.githubusercontent.com/4083812/121251846-fcbcdd80-c8af-11eb-84a4-152b0aacc0da.png)

**Comment by cs96and** [comment]
Exactly which thing do you want to change the colours of?  The typing notification?

**Comment by apoapostolov** [comment]
Hi @cs96and Yes, this is regarding the chat notification. I want to be able to set the background and the font color, to something that fits my current themes (or less colorful basic theme).

**Comment by cs96and** [comment]
I'm thinking of re-doing the typing notification anyway, so it's not quite so garish.  E.g...

![image](https://user-images.githubusercontent.com/898086/121921992-7251ff00-cd31-11eb-91f3-98054def53aa.png)

This is now a pop up that resizes the chat box slightly, rather than displaying over the top of other elements.

**Comment by cs96and** [comment]
The re-design of the typing notification is now in v0.2.2...

![](https://raw.githubusercontent.com/cs96and/FoundryVTT-CGMP/master/notify_typing.gif)
