### ISSUE TITLE
Pathfinder 2e Raise a Shield macro bug

### ISSUE THREAD

**Issue by ghost** [cs96and/FoundryVTT-CGMP#3]
In the Pathfinder 2e system, there's a macro for a character to Raise a Shield. However, when "Disable GM speaking as PC tokens" is enabled, the image for the shield is twice the size it's supposed to be when the GM uses the macro for player tokens.
![unknown](https://user-images.githubusercontent.com/83744909/123496685-36684500-d621-11eb-910f-5fc58802ed45.png)

**Comment by cs96and** [comment]
I've never used the pathfinder system.  Can you provide the steps on how to find and use this macro please?

**Comment by ghost** [comment]
It's in the Compendium Packs tab in Action Macros
![Untitled1](https://user-images.githubusercontent.com/83744909/123506616-0b034b80-d65d-11eb-9efb-7612c412093d.png)
And then it's the Raise a Shield macro
![Untitled2](https://user-images.githubusercontent.com/83744909/123506660-50277d80-d65d-11eb-8857-e57fb0278e18.png)

**Comment by cs96and** [comment]
I cannot re-create this issue.  I do notice that your screenshot is lightly different to mine though.  Your's says "Reactive shield" whereas mine says "Raise a shield"
![image](https://user-images.githubusercontent.com/898086/123551767-0d53cb80-d76b-11eb-8dcd-5848e11bfcd2.png)

I equipped a shield on a PC, dragged that macro to the quick bar, selected the PC token and clicked the macro.  Is there a different way to do it so that "reactive shield" is displayed instead?

**Comment by cs96and** [comment]
Aha, I worked it out.  You just have to click the macro when it is not that PCs turn in combat.  It makes no difference though, the shield icon still looks OK to me.
![image](https://user-images.githubusercontent.com/898086/123551891-abe02c80-d76b-11eb-9d0f-389ec2e6608b.png)

**Comment by cs96and** [comment]
OK, I've managed to re-create it now.  I just had to assign that PC to a player first :)  I'll see if I can work out what's causing it.

**Comment by cs96and** [comment]
086a7719cb0352a50f47f8973d3b780511fd4fc8

**Comment by cs96and** [comment]
Fixed in 0.2.4
